# Dependabot will run on day 21 of each month at 03:24 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 30
