name: Test and Release

# Run this job on all pushes and pull requests
# as well as tags with a semantic version
on:
  push:
    branches:
      - '*'
    tags:
      # normal versions
      - "v?[0-9]+.[0-9]+.[0-9]+"
      # pre-releases
      - "v?[0-9]+.[0-9]+.[0-9]+-**"
  pull_request: { }

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Lint the code
  check-and-lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm ci
      - name: Run linters
        run: npm run lint

  # Runs adapter tests on all supported node versions and OSes
  adapter-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    needs: check-and-lint

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 20.x, 22.x, 24.x ]
        os: [ ubuntu-latest ]

    steps:
      - uses: ioBroker/testing-action-adapter@v1
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

  # Deploys the final package to NPM (only if commit includes a version tag)
  deploy:
    needs: [ check-and-lint, adapter-tests ]

    # Trigger this step only when a commit on master is tagged with a version number
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: ioBroker/testing-action-deploy@v1
        with:
          node-version: 20.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Dummy job for skipped builds - without this, github reports the build as failed
  skip-ci:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip build
        run: echo "Build skipped!"
